//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace YamazakiMatex.Print.Table {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dtblTokuisakiMaster")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dtblTokuisakiMaster : global::System.Data.DataSet {
        
        private dtblTokuisakiMasterDataTable tabledtblTokuisakiMaster;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public dtblTokuisakiMaster() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected dtblTokuisakiMaster(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtblTokuisakiMaster"] != null)) {
                    base.Tables.Add(new dtblTokuisakiMasterDataTable(ds.Tables["dtblTokuisakiMaster"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtblTokuisakiMasterDataTable _dtblTokuisakiMaster {
            get {
                return this.tabledtblTokuisakiMaster;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dtblTokuisakiMaster cln = ((dtblTokuisakiMaster)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtblTokuisakiMaster"] != null)) {
                    base.Tables.Add(new dtblTokuisakiMasterDataTable(ds.Tables["dtblTokuisakiMaster"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledtblTokuisakiMaster = ((dtblTokuisakiMasterDataTable)(base.Tables["dtblTokuisakiMaster"]));
            if ((initTable == true)) {
                if ((this.tabledtblTokuisakiMaster != null)) {
                    this.tabledtblTokuisakiMaster.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dtblTokuisakiMaster";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dtblTokuisakiMaster.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtblTokuisakiMaster = new dtblTokuisakiMasterDataTable();
            base.Tables.Add(this.tabledtblTokuisakiMaster);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerialize_dtblTokuisakiMaster() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dtblTokuisakiMaster ds = new dtblTokuisakiMaster();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void dtblTokuisakiMasterRowChangeEventHandler(object sender, dtblTokuisakiMasterRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtblTokuisakiMasterDataTable : global::System.Data.TypedTableBase<dtblTokuisakiMasterRow> {
            
            private global::System.Data.DataColumn columntihou;
            
            private global::System.Data.DataColumn columntodouhuken;
            
            private global::System.Data.DataColumn columntokuisakiCode;
            
            private global::System.Data.DataColumn columntokuisakiName;
            
            private global::System.Data.DataColumn columntokuisakiKanaName1;
            
            private global::System.Data.DataColumn columntokuisakiKanaName2;
            
            private global::System.Data.DataColumn columnjigyousyoCode;
            
            private global::System.Data.DataColumn columnjigyousyoName;
            
            private global::System.Data.DataColumn columnyubinNo;
            
            private global::System.Data.DataColumn columnjusyo1;
            
            private global::System.Data.DataColumn columnjusyo2;
            
            private global::System.Data.DataColumn columnrenrakusaki1;
            
            private global::System.Data.DataColumn columnrenrakusaki2;
            
            private global::System.Data.DataColumn columntokuisakiTantousyaName;
            
            private global::System.Data.DataColumn columnshimebi;
            
            private global::System.Data.DataColumn columnseikyuKanriKubun;
            
            private global::System.Data.DataColumn columnparentTokuisakiCode;
            
            private global::System.Data.DataColumn columnparentJigyousyoCode;
            
            private global::System.Data.DataColumn columnkaisyuSaito;
            
            private global::System.Data.DataColumn columnkurikoshiSyuturyokuKubun;
            
            private global::System.Data.DataColumn columnseikyuSyuturyokuKubun;
            
            private global::System.Data.DataColumn columnmitumoriSyouhizei;
            
            private global::System.Data.DataColumn columnnouhinsyoSyouhizei;
            
            private global::System.Data.DataColumn columnhasuKubun;
            
            private global::System.Data.DataColumn columnkingakuHasuKubun;
            
            private global::System.Data.DataColumn columnsaisyuKoushinBi;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblTokuisakiMasterDataTable() {
                this.TableName = "dtblTokuisakiMaster";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal dtblTokuisakiMasterDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected dtblTokuisakiMasterDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn tihouColumn {
                get {
                    return this.columntihou;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn todouhukenColumn {
                get {
                    return this.columntodouhuken;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn tokuisakiCodeColumn {
                get {
                    return this.columntokuisakiCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn tokuisakiNameColumn {
                get {
                    return this.columntokuisakiName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn tokuisakiKanaName1Column {
                get {
                    return this.columntokuisakiKanaName1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn tokuisakiKanaName2Column {
                get {
                    return this.columntokuisakiKanaName2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn jigyousyoCodeColumn {
                get {
                    return this.columnjigyousyoCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn jigyousyoNameColumn {
                get {
                    return this.columnjigyousyoName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn yubinNoColumn {
                get {
                    return this.columnyubinNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn jusyo1Column {
                get {
                    return this.columnjusyo1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn jusyo2Column {
                get {
                    return this.columnjusyo2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn renrakusaki1Column {
                get {
                    return this.columnrenrakusaki1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn renrakusaki2Column {
                get {
                    return this.columnrenrakusaki2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn tokuisakiTantousyaNameColumn {
                get {
                    return this.columntokuisakiTantousyaName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn shimebiColumn {
                get {
                    return this.columnshimebi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn seikyuKanriKubunColumn {
                get {
                    return this.columnseikyuKanriKubun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn parentTokuisakiCodeColumn {
                get {
                    return this.columnparentTokuisakiCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn parentJigyousyoCodeColumn {
                get {
                    return this.columnparentJigyousyoCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn kaisyuSaitoColumn {
                get {
                    return this.columnkaisyuSaito;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn kurikoshiSyuturyokuKubunColumn {
                get {
                    return this.columnkurikoshiSyuturyokuKubun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn seikyuSyuturyokuKubunColumn {
                get {
                    return this.columnseikyuSyuturyokuKubun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn mitumoriSyouhizeiColumn {
                get {
                    return this.columnmitumoriSyouhizei;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn nouhinsyoSyouhizeiColumn {
                get {
                    return this.columnnouhinsyoSyouhizei;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn hasuKubunColumn {
                get {
                    return this.columnhasuKubun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn kingakuHasuKubunColumn {
                get {
                    return this.columnkingakuHasuKubun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn saisyuKoushinBiColumn {
                get {
                    return this.columnsaisyuKoushinBi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblTokuisakiMasterRow this[int index] {
                get {
                    return ((dtblTokuisakiMasterRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblTokuisakiMasterRowChangeEventHandler dtblTokuisakiMasterRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblTokuisakiMasterRowChangeEventHandler dtblTokuisakiMasterRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblTokuisakiMasterRowChangeEventHandler dtblTokuisakiMasterRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblTokuisakiMasterRowChangeEventHandler dtblTokuisakiMasterRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AdddtblTokuisakiMasterRow(dtblTokuisakiMasterRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblTokuisakiMasterRow AdddtblTokuisakiMasterRow(
                        string tihou, 
                        string todouhuken, 
                        string tokuisakiCode, 
                        string tokuisakiName, 
                        string tokuisakiKanaName1, 
                        string tokuisakiKanaName2, 
                        string jigyousyoCode, 
                        string jigyousyoName, 
                        string yubinNo, 
                        string jusyo1, 
                        string jusyo2, 
                        string renrakusaki1, 
                        string renrakusaki2, 
                        string tokuisakiTantousyaName, 
                        string shimebi, 
                        string seikyuKanriKubun, 
                        string parentTokuisakiCode, 
                        string parentJigyousyoCode, 
                        string kaisyuSaito, 
                        string kurikoshiSyuturyokuKubun, 
                        string seikyuSyuturyokuKubun, 
                        string mitumoriSyouhizei, 
                        string nouhinsyoSyouhizei, 
                        string hasuKubun, 
                        string kingakuHasuKubun, 
                        string saisyuKoushinBi) {
                dtblTokuisakiMasterRow rowdtblTokuisakiMasterRow = ((dtblTokuisakiMasterRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        tihou,
                        todouhuken,
                        tokuisakiCode,
                        tokuisakiName,
                        tokuisakiKanaName1,
                        tokuisakiKanaName2,
                        jigyousyoCode,
                        jigyousyoName,
                        yubinNo,
                        jusyo1,
                        jusyo2,
                        renrakusaki1,
                        renrakusaki2,
                        tokuisakiTantousyaName,
                        shimebi,
                        seikyuKanriKubun,
                        parentTokuisakiCode,
                        parentJigyousyoCode,
                        kaisyuSaito,
                        kurikoshiSyuturyokuKubun,
                        seikyuSyuturyokuKubun,
                        mitumoriSyouhizei,
                        nouhinsyoSyouhizei,
                        hasuKubun,
                        kingakuHasuKubun,
                        saisyuKoushinBi};
                rowdtblTokuisakiMasterRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtblTokuisakiMasterRow);
                return rowdtblTokuisakiMasterRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dtblTokuisakiMasterDataTable cln = ((dtblTokuisakiMasterDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtblTokuisakiMasterDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columntihou = base.Columns["tihou"];
                this.columntodouhuken = base.Columns["todouhuken"];
                this.columntokuisakiCode = base.Columns["tokuisakiCode"];
                this.columntokuisakiName = base.Columns["tokuisakiName"];
                this.columntokuisakiKanaName1 = base.Columns["tokuisakiKanaName1"];
                this.columntokuisakiKanaName2 = base.Columns["tokuisakiKanaName2"];
                this.columnjigyousyoCode = base.Columns["jigyousyoCode"];
                this.columnjigyousyoName = base.Columns["jigyousyoName"];
                this.columnyubinNo = base.Columns["yubinNo"];
                this.columnjusyo1 = base.Columns["jusyo1"];
                this.columnjusyo2 = base.Columns["jusyo2"];
                this.columnrenrakusaki1 = base.Columns["renrakusaki1"];
                this.columnrenrakusaki2 = base.Columns["renrakusaki2"];
                this.columntokuisakiTantousyaName = base.Columns["tokuisakiTantousyaName"];
                this.columnshimebi = base.Columns["shimebi"];
                this.columnseikyuKanriKubun = base.Columns["seikyuKanriKubun"];
                this.columnparentTokuisakiCode = base.Columns["parentTokuisakiCode"];
                this.columnparentJigyousyoCode = base.Columns["parentJigyousyoCode"];
                this.columnkaisyuSaito = base.Columns["kaisyuSaito"];
                this.columnkurikoshiSyuturyokuKubun = base.Columns["kurikoshiSyuturyokuKubun"];
                this.columnseikyuSyuturyokuKubun = base.Columns["seikyuSyuturyokuKubun"];
                this.columnmitumoriSyouhizei = base.Columns["mitumoriSyouhizei"];
                this.columnnouhinsyoSyouhizei = base.Columns["nouhinsyoSyouhizei"];
                this.columnhasuKubun = base.Columns["hasuKubun"];
                this.columnkingakuHasuKubun = base.Columns["kingakuHasuKubun"];
                this.columnsaisyuKoushinBi = base.Columns["saisyuKoushinBi"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columntihou = new global::System.Data.DataColumn("tihou", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntihou);
                this.columntodouhuken = new global::System.Data.DataColumn("todouhuken", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntodouhuken);
                this.columntokuisakiCode = new global::System.Data.DataColumn("tokuisakiCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntokuisakiCode);
                this.columntokuisakiName = new global::System.Data.DataColumn("tokuisakiName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntokuisakiName);
                this.columntokuisakiKanaName1 = new global::System.Data.DataColumn("tokuisakiKanaName1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntokuisakiKanaName1);
                this.columntokuisakiKanaName2 = new global::System.Data.DataColumn("tokuisakiKanaName2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntokuisakiKanaName2);
                this.columnjigyousyoCode = new global::System.Data.DataColumn("jigyousyoCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnjigyousyoCode);
                this.columnjigyousyoName = new global::System.Data.DataColumn("jigyousyoName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnjigyousyoName);
                this.columnyubinNo = new global::System.Data.DataColumn("yubinNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnyubinNo);
                this.columnjusyo1 = new global::System.Data.DataColumn("jusyo1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnjusyo1);
                this.columnjusyo2 = new global::System.Data.DataColumn("jusyo2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnjusyo2);
                this.columnrenrakusaki1 = new global::System.Data.DataColumn("renrakusaki1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrenrakusaki1);
                this.columnrenrakusaki2 = new global::System.Data.DataColumn("renrakusaki2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrenrakusaki2);
                this.columntokuisakiTantousyaName = new global::System.Data.DataColumn("tokuisakiTantousyaName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntokuisakiTantousyaName);
                this.columnshimebi = new global::System.Data.DataColumn("shimebi", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshimebi);
                this.columnseikyuKanriKubun = new global::System.Data.DataColumn("seikyuKanriKubun", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnseikyuKanriKubun);
                this.columnparentTokuisakiCode = new global::System.Data.DataColumn("parentTokuisakiCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnparentTokuisakiCode);
                this.columnparentJigyousyoCode = new global::System.Data.DataColumn("parentJigyousyoCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnparentJigyousyoCode);
                this.columnkaisyuSaito = new global::System.Data.DataColumn("kaisyuSaito", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkaisyuSaito);
                this.columnkurikoshiSyuturyokuKubun = new global::System.Data.DataColumn("kurikoshiSyuturyokuKubun", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkurikoshiSyuturyokuKubun);
                this.columnseikyuSyuturyokuKubun = new global::System.Data.DataColumn("seikyuSyuturyokuKubun", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnseikyuSyuturyokuKubun);
                this.columnmitumoriSyouhizei = new global::System.Data.DataColumn("mitumoriSyouhizei", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmitumoriSyouhizei);
                this.columnnouhinsyoSyouhizei = new global::System.Data.DataColumn("nouhinsyoSyouhizei", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnouhinsyoSyouhizei);
                this.columnhasuKubun = new global::System.Data.DataColumn("hasuKubun", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhasuKubun);
                this.columnkingakuHasuKubun = new global::System.Data.DataColumn("kingakuHasuKubun", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkingakuHasuKubun);
                this.columnsaisyuKoushinBi = new global::System.Data.DataColumn("saisyuKoushinBi", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsaisyuKoushinBi);
                this.ExtendedProperties.Add("Generator_TablePropName", "_dtblTokuisakiMaster");
                this.ExtendedProperties.Add("Generator_UserTableName", "dtblTokuisakiMaster");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblTokuisakiMasterRow NewdtblTokuisakiMasterRow() {
                return ((dtblTokuisakiMasterRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtblTokuisakiMasterRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dtblTokuisakiMasterRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtblTokuisakiMasterRowChanged != null)) {
                    this.dtblTokuisakiMasterRowChanged(this, new dtblTokuisakiMasterRowChangeEvent(((dtblTokuisakiMasterRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtblTokuisakiMasterRowChanging != null)) {
                    this.dtblTokuisakiMasterRowChanging(this, new dtblTokuisakiMasterRowChangeEvent(((dtblTokuisakiMasterRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtblTokuisakiMasterRowDeleted != null)) {
                    this.dtblTokuisakiMasterRowDeleted(this, new dtblTokuisakiMasterRowChangeEvent(((dtblTokuisakiMasterRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtblTokuisakiMasterRowDeleting != null)) {
                    this.dtblTokuisakiMasterRowDeleting(this, new dtblTokuisakiMasterRowChangeEvent(((dtblTokuisakiMasterRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemovedtblTokuisakiMasterRow(dtblTokuisakiMasterRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtblTokuisakiMaster ds = new dtblTokuisakiMaster();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtblTokuisakiMasterDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dtblTokuisakiMasterRow : global::System.Data.DataRow {
            
            private dtblTokuisakiMasterDataTable tabledtblTokuisakiMaster;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal dtblTokuisakiMasterRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtblTokuisakiMaster = ((dtblTokuisakiMasterDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string tihou {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.tihouColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'tihou\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.tihouColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string todouhuken {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.todouhukenColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'todouhuken\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.todouhukenColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string tokuisakiCode {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.tokuisakiCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'tokuisakiCode\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.tokuisakiCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string tokuisakiName {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.tokuisakiNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'tokuisakiName\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.tokuisakiNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string tokuisakiKanaName1 {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.tokuisakiKanaName1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'tokuisakiKanaName1\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.tokuisakiKanaName1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string tokuisakiKanaName2 {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.tokuisakiKanaName2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'tokuisakiKanaName2\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.tokuisakiKanaName2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string jigyousyoCode {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.jigyousyoCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'jigyousyoCode\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.jigyousyoCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string jigyousyoName {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.jigyousyoNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'jigyousyoName\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.jigyousyoNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string yubinNo {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.yubinNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'yubinNo\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.yubinNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string jusyo1 {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.jusyo1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'jusyo1\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.jusyo1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string jusyo2 {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.jusyo2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'jusyo2\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.jusyo2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string renrakusaki1 {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.renrakusaki1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'renrakusaki1\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.renrakusaki1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string renrakusaki2 {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.renrakusaki2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'renrakusaki2\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.renrakusaki2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string tokuisakiTantousyaName {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.tokuisakiTantousyaNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'tokuisakiTantousyaName\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.tokuisakiTantousyaNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string shimebi {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.shimebiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'shimebi\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.shimebiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string seikyuKanriKubun {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.seikyuKanriKubunColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'seikyuKanriKubun\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.seikyuKanriKubunColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string parentTokuisakiCode {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.parentTokuisakiCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'parentTokuisakiCode\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.parentTokuisakiCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string parentJigyousyoCode {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.parentJigyousyoCodeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'parentJigyousyoCode\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.parentJigyousyoCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string kaisyuSaito {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.kaisyuSaitoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'kaisyuSaito\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.kaisyuSaitoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string kurikoshiSyuturyokuKubun {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.kurikoshiSyuturyokuKubunColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'kurikoshiSyuturyokuKubun\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.kurikoshiSyuturyokuKubunColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string seikyuSyuturyokuKubun {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.seikyuSyuturyokuKubunColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'seikyuSyuturyokuKubun\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.seikyuSyuturyokuKubunColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string mitumoriSyouhizei {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.mitumoriSyouhizeiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'mitumoriSyouhizei\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.mitumoriSyouhizeiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string nouhinsyoSyouhizei {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.nouhinsyoSyouhizeiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'nouhinsyoSyouhizei\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.nouhinsyoSyouhizeiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string hasuKubun {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.hasuKubunColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'hasuKubun\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.hasuKubunColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string kingakuHasuKubun {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.kingakuHasuKubunColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'kingakuHasuKubun\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.kingakuHasuKubunColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string saisyuKoushinBi {
                get {
                    try {
                        return ((string)(this[this.tabledtblTokuisakiMaster.saisyuKoushinBiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblTokuisakiMaster\' にある列 \'saisyuKoushinBi\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblTokuisakiMaster.saisyuKoushinBiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstihouNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.tihouColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettihouNull() {
                this[this.tabledtblTokuisakiMaster.tihouColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstodouhukenNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.todouhukenColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettodouhukenNull() {
                this[this.tabledtblTokuisakiMaster.todouhukenColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstokuisakiCodeNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.tokuisakiCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettokuisakiCodeNull() {
                this[this.tabledtblTokuisakiMaster.tokuisakiCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstokuisakiNameNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.tokuisakiNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettokuisakiNameNull() {
                this[this.tabledtblTokuisakiMaster.tokuisakiNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstokuisakiKanaName1Null() {
                return this.IsNull(this.tabledtblTokuisakiMaster.tokuisakiKanaName1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettokuisakiKanaName1Null() {
                this[this.tabledtblTokuisakiMaster.tokuisakiKanaName1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstokuisakiKanaName2Null() {
                return this.IsNull(this.tabledtblTokuisakiMaster.tokuisakiKanaName2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettokuisakiKanaName2Null() {
                this[this.tabledtblTokuisakiMaster.tokuisakiKanaName2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsjigyousyoCodeNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.jigyousyoCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetjigyousyoCodeNull() {
                this[this.tabledtblTokuisakiMaster.jigyousyoCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsjigyousyoNameNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.jigyousyoNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetjigyousyoNameNull() {
                this[this.tabledtblTokuisakiMaster.jigyousyoNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsyubinNoNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.yubinNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetyubinNoNull() {
                this[this.tabledtblTokuisakiMaster.yubinNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool Isjusyo1Null() {
                return this.IsNull(this.tabledtblTokuisakiMaster.jusyo1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void Setjusyo1Null() {
                this[this.tabledtblTokuisakiMaster.jusyo1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool Isjusyo2Null() {
                return this.IsNull(this.tabledtblTokuisakiMaster.jusyo2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void Setjusyo2Null() {
                this[this.tabledtblTokuisakiMaster.jusyo2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool Isrenrakusaki1Null() {
                return this.IsNull(this.tabledtblTokuisakiMaster.renrakusaki1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void Setrenrakusaki1Null() {
                this[this.tabledtblTokuisakiMaster.renrakusaki1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool Isrenrakusaki2Null() {
                return this.IsNull(this.tabledtblTokuisakiMaster.renrakusaki2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void Setrenrakusaki2Null() {
                this[this.tabledtblTokuisakiMaster.renrakusaki2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstokuisakiTantousyaNameNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.tokuisakiTantousyaNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettokuisakiTantousyaNameNull() {
                this[this.tabledtblTokuisakiMaster.tokuisakiTantousyaNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsshimebiNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.shimebiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetshimebiNull() {
                this[this.tabledtblTokuisakiMaster.shimebiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsseikyuKanriKubunNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.seikyuKanriKubunColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetseikyuKanriKubunNull() {
                this[this.tabledtblTokuisakiMaster.seikyuKanriKubunColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsparentTokuisakiCodeNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.parentTokuisakiCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetparentTokuisakiCodeNull() {
                this[this.tabledtblTokuisakiMaster.parentTokuisakiCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsparentJigyousyoCodeNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.parentJigyousyoCodeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetparentJigyousyoCodeNull() {
                this[this.tabledtblTokuisakiMaster.parentJigyousyoCodeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IskaisyuSaitoNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.kaisyuSaitoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetkaisyuSaitoNull() {
                this[this.tabledtblTokuisakiMaster.kaisyuSaitoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IskurikoshiSyuturyokuKubunNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.kurikoshiSyuturyokuKubunColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetkurikoshiSyuturyokuKubunNull() {
                this[this.tabledtblTokuisakiMaster.kurikoshiSyuturyokuKubunColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsseikyuSyuturyokuKubunNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.seikyuSyuturyokuKubunColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetseikyuSyuturyokuKubunNull() {
                this[this.tabledtblTokuisakiMaster.seikyuSyuturyokuKubunColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsmitumoriSyouhizeiNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.mitumoriSyouhizeiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetmitumoriSyouhizeiNull() {
                this[this.tabledtblTokuisakiMaster.mitumoriSyouhizeiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsnouhinsyoSyouhizeiNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.nouhinsyoSyouhizeiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetnouhinsyoSyouhizeiNull() {
                this[this.tabledtblTokuisakiMaster.nouhinsyoSyouhizeiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IshasuKubunNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.hasuKubunColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SethasuKubunNull() {
                this[this.tabledtblTokuisakiMaster.hasuKubunColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IskingakuHasuKubunNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.kingakuHasuKubunColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetkingakuHasuKubunNull() {
                this[this.tabledtblTokuisakiMaster.kingakuHasuKubunColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IssaisyuKoushinBiNull() {
                return this.IsNull(this.tabledtblTokuisakiMaster.saisyuKoushinBiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetsaisyuKoushinBiNull() {
                this[this.tabledtblTokuisakiMaster.saisyuKoushinBiColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class dtblTokuisakiMasterRowChangeEvent : global::System.EventArgs {
            
            private dtblTokuisakiMasterRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblTokuisakiMasterRowChangeEvent(dtblTokuisakiMasterRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblTokuisakiMasterRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591