//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace YamazakiMatex.Print.Table {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dtblKaikakeZandakaIchiran")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dtblKaikakeZandakaIchiran : global::System.Data.DataSet {
        
        private dtblKaikakeZandakaIchiranDataTable tabledtblKaikakeZandakaIchiran;
        
        private dtblKaikakeZandakaIchiranGDataTable tabledtblKaikakeZandakaIchiranG;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public dtblKaikakeZandakaIchiran() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected dtblKaikakeZandakaIchiran(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtblKaikakeZandakaIchiran"] != null)) {
                    base.Tables.Add(new dtblKaikakeZandakaIchiranDataTable(ds.Tables["dtblKaikakeZandakaIchiran"]));
                }
                if ((ds.Tables["dtblKaikakeZandakaIchiranG"] != null)) {
                    base.Tables.Add(new dtblKaikakeZandakaIchiranGDataTable(ds.Tables["dtblKaikakeZandakaIchiranG"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtblKaikakeZandakaIchiranDataTable _dtblKaikakeZandakaIchiran {
            get {
                return this.tabledtblKaikakeZandakaIchiran;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtblKaikakeZandakaIchiranGDataTable dtblKaikakeZandakaIchiranG {
            get {
                return this.tabledtblKaikakeZandakaIchiranG;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dtblKaikakeZandakaIchiran cln = ((dtblKaikakeZandakaIchiran)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtblKaikakeZandakaIchiran"] != null)) {
                    base.Tables.Add(new dtblKaikakeZandakaIchiranDataTable(ds.Tables["dtblKaikakeZandakaIchiran"]));
                }
                if ((ds.Tables["dtblKaikakeZandakaIchiranG"] != null)) {
                    base.Tables.Add(new dtblKaikakeZandakaIchiranGDataTable(ds.Tables["dtblKaikakeZandakaIchiranG"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledtblKaikakeZandakaIchiran = ((dtblKaikakeZandakaIchiranDataTable)(base.Tables["dtblKaikakeZandakaIchiran"]));
            if ((initTable == true)) {
                if ((this.tabledtblKaikakeZandakaIchiran != null)) {
                    this.tabledtblKaikakeZandakaIchiran.InitVars();
                }
            }
            this.tabledtblKaikakeZandakaIchiranG = ((dtblKaikakeZandakaIchiranGDataTable)(base.Tables["dtblKaikakeZandakaIchiranG"]));
            if ((initTable == true)) {
                if ((this.tabledtblKaikakeZandakaIchiranG != null)) {
                    this.tabledtblKaikakeZandakaIchiranG.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dtblKaikakeZandakaIchiran";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dtblKaikakeZandakaIchiran.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtblKaikakeZandakaIchiran = new dtblKaikakeZandakaIchiranDataTable();
            base.Tables.Add(this.tabledtblKaikakeZandakaIchiran);
            this.tabledtblKaikakeZandakaIchiranG = new dtblKaikakeZandakaIchiranGDataTable();
            base.Tables.Add(this.tabledtblKaikakeZandakaIchiranG);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerialize_dtblKaikakeZandakaIchiran() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializedtblKaikakeZandakaIchiranG() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dtblKaikakeZandakaIchiran ds = new dtblKaikakeZandakaIchiran();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void dtblKaikakeZandakaIchiranRowChangeEventHandler(object sender, dtblKaikakeZandakaIchiranRowChangeEvent e);
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void dtblKaikakeZandakaIchiranGRowChangeEventHandler(object sender, dtblKaikakeZandakaIchiranGRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtblKaikakeZandakaIchiranDataTable : global::System.Data.TypedTableBase<dtblKaikakeZandakaIchiranRow> {
            
            private global::System.Data.DataColumn columnnen;
            
            private global::System.Data.DataColumn columntuki;
            
            private global::System.Data.DataColumn columnshiireCd;
            
            private global::System.Data.DataColumn columnshiireNm;
            
            private global::System.Data.DataColumn columnzengetuZan;
            
            private global::System.Data.DataColumn columntogetuShiire;
            
            private global::System.Data.DataColumn columntogetuShohizei;
            
            private global::System.Data.DataColumn columntogetuShiireG;
            
            private global::System.Data.DataColumn columntogetuShiharai;
            
            private global::System.Data.DataColumn columntogetuZan;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranDataTable() {
                this.TableName = "dtblKaikakeZandakaIchiran";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal dtblKaikakeZandakaIchiranDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected dtblKaikakeZandakaIchiranDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn nenColumn {
                get {
                    return this.columnnen;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn tukiColumn {
                get {
                    return this.columntuki;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn shiireCdColumn {
                get {
                    return this.columnshiireCd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn shiireNmColumn {
                get {
                    return this.columnshiireNm;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn zengetuZanColumn {
                get {
                    return this.columnzengetuZan;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuShiireColumn {
                get {
                    return this.columntogetuShiire;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuShohizeiColumn {
                get {
                    return this.columntogetuShohizei;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuShiireGColumn {
                get {
                    return this.columntogetuShiireG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuShiharaiColumn {
                get {
                    return this.columntogetuShiharai;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuZanColumn {
                get {
                    return this.columntogetuZan;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranRow this[int index] {
                get {
                    return ((dtblKaikakeZandakaIchiranRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblKaikakeZandakaIchiranRowChangeEventHandler dtblKaikakeZandakaIchiranRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblKaikakeZandakaIchiranRowChangeEventHandler dtblKaikakeZandakaIchiranRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblKaikakeZandakaIchiranRowChangeEventHandler dtblKaikakeZandakaIchiranRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblKaikakeZandakaIchiranRowChangeEventHandler dtblKaikakeZandakaIchiranRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AdddtblKaikakeZandakaIchiranRow(dtblKaikakeZandakaIchiranRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranRow AdddtblKaikakeZandakaIchiranRow(string nen, string tuki, string shiireCd, string shiireNm, string zengetuZan, string togetuShiire, string togetuShohizei, string togetuShiireG, string togetuShiharai, string togetuZan) {
                dtblKaikakeZandakaIchiranRow rowdtblKaikakeZandakaIchiranRow = ((dtblKaikakeZandakaIchiranRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        nen,
                        tuki,
                        shiireCd,
                        shiireNm,
                        zengetuZan,
                        togetuShiire,
                        togetuShohizei,
                        togetuShiireG,
                        togetuShiharai,
                        togetuZan};
                rowdtblKaikakeZandakaIchiranRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtblKaikakeZandakaIchiranRow);
                return rowdtblKaikakeZandakaIchiranRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dtblKaikakeZandakaIchiranDataTable cln = ((dtblKaikakeZandakaIchiranDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtblKaikakeZandakaIchiranDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnnen = base.Columns["nen"];
                this.columntuki = base.Columns["tuki"];
                this.columnshiireCd = base.Columns["shiireCd"];
                this.columnshiireNm = base.Columns["shiireNm"];
                this.columnzengetuZan = base.Columns["zengetuZan"];
                this.columntogetuShiire = base.Columns["togetuShiire"];
                this.columntogetuShohizei = base.Columns["togetuShohizei"];
                this.columntogetuShiireG = base.Columns["togetuShiireG"];
                this.columntogetuShiharai = base.Columns["togetuShiharai"];
                this.columntogetuZan = base.Columns["togetuZan"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnnen = new global::System.Data.DataColumn("nen", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnen);
                this.columntuki = new global::System.Data.DataColumn("tuki", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntuki);
                this.columnshiireCd = new global::System.Data.DataColumn("shiireCd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshiireCd);
                this.columnshiireNm = new global::System.Data.DataColumn("shiireNm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshiireNm);
                this.columnzengetuZan = new global::System.Data.DataColumn("zengetuZan", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnzengetuZan);
                this.columntogetuShiire = new global::System.Data.DataColumn("togetuShiire", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuShiire);
                this.columntogetuShohizei = new global::System.Data.DataColumn("togetuShohizei", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuShohizei);
                this.columntogetuShiireG = new global::System.Data.DataColumn("togetuShiireG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuShiireG);
                this.columntogetuShiharai = new global::System.Data.DataColumn("togetuShiharai", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuShiharai);
                this.columntogetuZan = new global::System.Data.DataColumn("togetuZan", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuZan);
                this.ExtendedProperties.Add("Generator_TablePropName", "_dtblKaikakeZandakaIchiran");
                this.ExtendedProperties.Add("Generator_UserTableName", "dtblKaikakeZandakaIchiran");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranRow NewdtblKaikakeZandakaIchiranRow() {
                return ((dtblKaikakeZandakaIchiranRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtblKaikakeZandakaIchiranRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dtblKaikakeZandakaIchiranRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtblKaikakeZandakaIchiranRowChanged != null)) {
                    this.dtblKaikakeZandakaIchiranRowChanged(this, new dtblKaikakeZandakaIchiranRowChangeEvent(((dtblKaikakeZandakaIchiranRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtblKaikakeZandakaIchiranRowChanging != null)) {
                    this.dtblKaikakeZandakaIchiranRowChanging(this, new dtblKaikakeZandakaIchiranRowChangeEvent(((dtblKaikakeZandakaIchiranRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtblKaikakeZandakaIchiranRowDeleted != null)) {
                    this.dtblKaikakeZandakaIchiranRowDeleted(this, new dtblKaikakeZandakaIchiranRowChangeEvent(((dtblKaikakeZandakaIchiranRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtblKaikakeZandakaIchiranRowDeleting != null)) {
                    this.dtblKaikakeZandakaIchiranRowDeleting(this, new dtblKaikakeZandakaIchiranRowChangeEvent(((dtblKaikakeZandakaIchiranRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemovedtblKaikakeZandakaIchiranRow(dtblKaikakeZandakaIchiranRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtblKaikakeZandakaIchiran ds = new dtblKaikakeZandakaIchiran();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtblKaikakeZandakaIchiranDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtblKaikakeZandakaIchiranGDataTable : global::System.Data.TypedTableBase<dtblKaikakeZandakaIchiranGRow> {
            
            private global::System.Data.DataColumn columnnen;
            
            private global::System.Data.DataColumn columntuki;
            
            private global::System.Data.DataColumn columnzengetuZanG;
            
            private global::System.Data.DataColumn columntogetuShiireG;
            
            private global::System.Data.DataColumn columntogetuShohizeiG;
            
            private global::System.Data.DataColumn columntogetuShiireGG;
            
            private global::System.Data.DataColumn columntogetuShiharaiG;
            
            private global::System.Data.DataColumn columntogetuZanG;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranGDataTable() {
                this.TableName = "dtblKaikakeZandakaIchiranG";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal dtblKaikakeZandakaIchiranGDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected dtblKaikakeZandakaIchiranGDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn nenColumn {
                get {
                    return this.columnnen;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn tukiColumn {
                get {
                    return this.columntuki;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn zengetuZanGColumn {
                get {
                    return this.columnzengetuZanG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuShiireGColumn {
                get {
                    return this.columntogetuShiireG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuShohizeiGColumn {
                get {
                    return this.columntogetuShohizeiG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuShiireGGColumn {
                get {
                    return this.columntogetuShiireGG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuShiharaiGColumn {
                get {
                    return this.columntogetuShiharaiG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn togetuZanGColumn {
                get {
                    return this.columntogetuZanG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranGRow this[int index] {
                get {
                    return ((dtblKaikakeZandakaIchiranGRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblKaikakeZandakaIchiranGRowChangeEventHandler dtblKaikakeZandakaIchiranGRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblKaikakeZandakaIchiranGRowChangeEventHandler dtblKaikakeZandakaIchiranGRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblKaikakeZandakaIchiranGRowChangeEventHandler dtblKaikakeZandakaIchiranGRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event dtblKaikakeZandakaIchiranGRowChangeEventHandler dtblKaikakeZandakaIchiranGRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AdddtblKaikakeZandakaIchiranGRow(dtblKaikakeZandakaIchiranGRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranGRow AdddtblKaikakeZandakaIchiranGRow(string nen, string tuki, string zengetuZanG, string togetuShiireG, string togetuShohizeiG, string togetuShiireGG, string togetuShiharaiG, string togetuZanG) {
                dtblKaikakeZandakaIchiranGRow rowdtblKaikakeZandakaIchiranGRow = ((dtblKaikakeZandakaIchiranGRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        nen,
                        tuki,
                        zengetuZanG,
                        togetuShiireG,
                        togetuShohizeiG,
                        togetuShiireGG,
                        togetuShiharaiG,
                        togetuZanG};
                rowdtblKaikakeZandakaIchiranGRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtblKaikakeZandakaIchiranGRow);
                return rowdtblKaikakeZandakaIchiranGRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dtblKaikakeZandakaIchiranGDataTable cln = ((dtblKaikakeZandakaIchiranGDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtblKaikakeZandakaIchiranGDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnnen = base.Columns["nen"];
                this.columntuki = base.Columns["tuki"];
                this.columnzengetuZanG = base.Columns["zengetuZanG"];
                this.columntogetuShiireG = base.Columns["togetuShiireG"];
                this.columntogetuShohizeiG = base.Columns["togetuShohizeiG"];
                this.columntogetuShiireGG = base.Columns["togetuShiireGG"];
                this.columntogetuShiharaiG = base.Columns["togetuShiharaiG"];
                this.columntogetuZanG = base.Columns["togetuZanG"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnnen = new global::System.Data.DataColumn("nen", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnen);
                this.columntuki = new global::System.Data.DataColumn("tuki", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntuki);
                this.columnzengetuZanG = new global::System.Data.DataColumn("zengetuZanG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnzengetuZanG);
                this.columntogetuShiireG = new global::System.Data.DataColumn("togetuShiireG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuShiireG);
                this.columntogetuShohizeiG = new global::System.Data.DataColumn("togetuShohizeiG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuShohizeiG);
                this.columntogetuShiireGG = new global::System.Data.DataColumn("togetuShiireGG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuShiireGG);
                this.columntogetuShiharaiG = new global::System.Data.DataColumn("togetuShiharaiG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuShiharaiG);
                this.columntogetuZanG = new global::System.Data.DataColumn("togetuZanG", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntogetuZanG);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranGRow NewdtblKaikakeZandakaIchiranGRow() {
                return ((dtblKaikakeZandakaIchiranGRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtblKaikakeZandakaIchiranGRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dtblKaikakeZandakaIchiranGRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtblKaikakeZandakaIchiranGRowChanged != null)) {
                    this.dtblKaikakeZandakaIchiranGRowChanged(this, new dtblKaikakeZandakaIchiranGRowChangeEvent(((dtblKaikakeZandakaIchiranGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtblKaikakeZandakaIchiranGRowChanging != null)) {
                    this.dtblKaikakeZandakaIchiranGRowChanging(this, new dtblKaikakeZandakaIchiranGRowChangeEvent(((dtblKaikakeZandakaIchiranGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtblKaikakeZandakaIchiranGRowDeleted != null)) {
                    this.dtblKaikakeZandakaIchiranGRowDeleted(this, new dtblKaikakeZandakaIchiranGRowChangeEvent(((dtblKaikakeZandakaIchiranGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtblKaikakeZandakaIchiranGRowDeleting != null)) {
                    this.dtblKaikakeZandakaIchiranGRowDeleting(this, new dtblKaikakeZandakaIchiranGRowChangeEvent(((dtblKaikakeZandakaIchiranGRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemovedtblKaikakeZandakaIchiranGRow(dtblKaikakeZandakaIchiranGRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dtblKaikakeZandakaIchiran ds = new dtblKaikakeZandakaIchiran();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtblKaikakeZandakaIchiranGDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dtblKaikakeZandakaIchiranRow : global::System.Data.DataRow {
            
            private dtblKaikakeZandakaIchiranDataTable tabledtblKaikakeZandakaIchiran;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal dtblKaikakeZandakaIchiranRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtblKaikakeZandakaIchiran = ((dtblKaikakeZandakaIchiranDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string nen {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.nenColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'nen\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.nenColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string tuki {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.tukiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'tuki\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.tukiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string shiireCd {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.shiireCdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'shiireCd\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.shiireCdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string shiireNm {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.shiireNmColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'shiireNm\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.shiireNmColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string zengetuZan {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.zengetuZanColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'zengetuZan\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.zengetuZanColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuShiire {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.togetuShiireColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'togetuShiire\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.togetuShiireColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuShohizei {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.togetuShohizeiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'togetuShohizei\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.togetuShohizeiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuShiireG {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.togetuShiireGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'togetuShiireG\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.togetuShiireGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuShiharai {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.togetuShiharaiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'togetuShiharai\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.togetuShiharaiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuZan {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiran.togetuZanColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiran\' にある列 \'togetuZan\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiran.togetuZanColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsnenNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.nenColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetnenNull() {
                this[this.tabledtblKaikakeZandakaIchiran.nenColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstukiNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.tukiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettukiNull() {
                this[this.tabledtblKaikakeZandakaIchiran.tukiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsshiireCdNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.shiireCdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetshiireCdNull() {
                this[this.tabledtblKaikakeZandakaIchiran.shiireCdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsshiireNmNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.shiireNmColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetshiireNmNull() {
                this[this.tabledtblKaikakeZandakaIchiran.shiireNmColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IszengetuZanNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.zengetuZanColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetzengetuZanNull() {
                this[this.tabledtblKaikakeZandakaIchiran.zengetuZanColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuShiireNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.togetuShiireColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuShiireNull() {
                this[this.tabledtblKaikakeZandakaIchiran.togetuShiireColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuShohizeiNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.togetuShohizeiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuShohizeiNull() {
                this[this.tabledtblKaikakeZandakaIchiran.togetuShohizeiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuShiireGNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.togetuShiireGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuShiireGNull() {
                this[this.tabledtblKaikakeZandakaIchiran.togetuShiireGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuShiharaiNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.togetuShiharaiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuShiharaiNull() {
                this[this.tabledtblKaikakeZandakaIchiran.togetuShiharaiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuZanNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiran.togetuZanColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuZanNull() {
                this[this.tabledtblKaikakeZandakaIchiran.togetuZanColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dtblKaikakeZandakaIchiranGRow : global::System.Data.DataRow {
            
            private dtblKaikakeZandakaIchiranGDataTable tabledtblKaikakeZandakaIchiranG;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal dtblKaikakeZandakaIchiranGRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtblKaikakeZandakaIchiranG = ((dtblKaikakeZandakaIchiranGDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string nen {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiranG.nenColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiranG\' にある列 \'nen\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiranG.nenColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string tuki {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiranG.tukiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiranG\' にある列 \'tuki\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiranG.tukiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string zengetuZanG {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiranG.zengetuZanGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiranG\' にある列 \'zengetuZanG\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiranG.zengetuZanGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuShiireG {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiranG.togetuShiireGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiranG\' にある列 \'togetuShiireG\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiranG.togetuShiireGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuShohizeiG {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiranG.togetuShohizeiGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiranG\' にある列 \'togetuShohizeiG\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiranG.togetuShohizeiGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuShiireGG {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiranG.togetuShiireGGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiranG\' にある列 \'togetuShiireGG\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiranG.togetuShiireGGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuShiharaiG {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiranG.togetuShiharaiGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiranG\' にある列 \'togetuShiharaiG\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiranG.togetuShiharaiGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string togetuZanG {
                get {
                    try {
                        return ((string)(this[this.tabledtblKaikakeZandakaIchiranG.togetuZanGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'dtblKaikakeZandakaIchiranG\' にある列 \'togetuZanG\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tabledtblKaikakeZandakaIchiranG.togetuZanGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsnenNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiranG.nenColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetnenNull() {
                this[this.tabledtblKaikakeZandakaIchiranG.nenColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstukiNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiranG.tukiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettukiNull() {
                this[this.tabledtblKaikakeZandakaIchiranG.tukiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IszengetuZanGNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiranG.zengetuZanGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetzengetuZanGNull() {
                this[this.tabledtblKaikakeZandakaIchiranG.zengetuZanGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuShiireGNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiranG.togetuShiireGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuShiireGNull() {
                this[this.tabledtblKaikakeZandakaIchiranG.togetuShiireGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuShohizeiGNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiranG.togetuShohizeiGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuShohizeiGNull() {
                this[this.tabledtblKaikakeZandakaIchiranG.togetuShohizeiGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuShiireGGNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiranG.togetuShiireGGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuShiireGGNull() {
                this[this.tabledtblKaikakeZandakaIchiranG.togetuShiireGGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuShiharaiGNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiranG.togetuShiharaiGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuShiharaiGNull() {
                this[this.tabledtblKaikakeZandakaIchiranG.togetuShiharaiGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IstogetuZanGNull() {
                return this.IsNull(this.tabledtblKaikakeZandakaIchiranG.togetuZanGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SettogetuZanGNull() {
                this[this.tabledtblKaikakeZandakaIchiranG.togetuZanGColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class dtblKaikakeZandakaIchiranRowChangeEvent : global::System.EventArgs {
            
            private dtblKaikakeZandakaIchiranRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranRowChangeEvent(dtblKaikakeZandakaIchiranRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class dtblKaikakeZandakaIchiranGRowChangeEvent : global::System.EventArgs {
            
            private dtblKaikakeZandakaIchiranGRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranGRowChangeEvent(dtblKaikakeZandakaIchiranGRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public dtblKaikakeZandakaIchiranGRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591